catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/',views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/',views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('cart/add/<str:isbn>/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.cart_detail, name='cart-detail'),
    path('books-per-author/', views.books_per_author, name='books_per_author'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed-books/', views.view_loaned_book_librarian.as_view(), name='borrowed-books'),
    path('cart/checkout/', views.checkout, name='checkout'),
    path('cart/checkout/success/', views.checkout_success, name='checkout-success'),
    path('update-cart-item/', views.update_cart_item_quantity, name='update_cart_item_quantity'),
    path('register/', views.register, name='register'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/',include('catalog.urls')),
    path('',RedirectView.as_view(url='catalog/',permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

#Make app use local files for pictures and stuffs
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse # Used in get_absolute_url() to get URL for specified ID

from django.db.models import UniqueConstraint # Constrains fields to unique values
from django.db.models.functions import Lower # Returns lower cased value of field

from django.conf import settings
from datetime import date

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a particular genre instance."""
        return reverse('genre-detail', args=[str(self.id)])

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='genre_name_case_insensitive_unique',
                violation_error_message = "Genre already exists (case insensitive match)"
            ),
        ]
    


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books.
    # Author as a string rather than object because it hasn't been declared yet in file.

    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(
        Genre, help_text="Select a genre for this book")
    
    price = models.DecimalField(max_digits=6, decimal_places=2, help_text="Price of this book",default=0.00)

    price_choices=[
        ('USD','United State Dollars'),
        ('VND','Vietnamese Dong'),
    ]
    price_unit=models.CharField(
        max_length=3,
        choices=price_choices,
        default='USD',
        help_text='Choose the unit of the price',
        null=True,
    )

    Language_choices=[
        ('en','English'),
        ('vn','Vietnamese'),
    ]
    
    language=models.CharField(
        max_length=2,
        choices=Language_choices,
        default='en',
        help_text='Choose the language that the book is written in',
    )
    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    


import uuid # Required for unique book instances

class BookInstance(models.Model):

    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)


    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
    


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.first_name} {self.last_name}'


class Cart(models.Model):
    """Model representing a shopping cart."""
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)  # Assuming you want to associate a cart with a user
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String for representing the Cart object."""
        return f'Cart {self.id} for {self.user.username}'


class CartItem(models.Model):
    """Model representing an item in the shopping cart."""
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, to_field='isbn')
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        """String for representing the CartItem object."""
        return f'{self.quantity} of {self.book.title}'

class Inventory(models.Model):
    """Model representing the inventory of books in the library."""
    book = models.OneToOneField('Book', on_delete=models.CASCADE, primary_key=True)
    quantity_available = models.PositiveIntegerField(default=0)

    def __str__(self):
        """String for representing the Inventory object."""
        return f'{self.book.title} - Available: {self.quantity_available}'

    class Meta:
        verbose_name = "Inventory"
        verbose_name_plural = "Inventories"

catalog/forms.py
import datetime

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from django.contrib.auth.models import User

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data
    

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password != password_confirm:
            raise forms.ValidationError("Passwords do not match.")

catalog/templates/base_generic.html
<!doctype html>
<html lang="en">
  <head>
    {% block title %}
      <title>Sach Cua Toi</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"> -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <script src="{% static 'script/script.js' %}"></script>
    
  </head>
  <body>
    
      <header>
        {% block menu %}
          <div class="logo">
          </div>
          <div class="menu">
              <li><a href="{%url 'books'%}">Sách</a></li>
              <li><a href="{%url 'authors'%}">Tác giả</a></li>
                {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                    <li>
                    <form id="logout-form" method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link">Logout</button>
                    </form>
                    </li>
                    <li><a href="{% url 'cart-detail'%}"> Cart </a> </li>
                    
                    

                    {% if user.is_staff %}
                    <li><a href="{% url 'borrowed-books' %}">Borrowed</a></li>
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a href="{% url 'books_per_author'%}"> Bieu Do </a> </li>
                    {%else%}
                    <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>

                    {%endif%}
                    
                {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                    <li><a href="{% url 'register' %}">Register</a></li>
                {% endif %}

            
          <div class="other">
              <li><input placeholder="Nhập từ cần tìm" type="text"> <i class="fas fa-search"></i></li>
              <li><a class="fa fa-shopping-bag" href=""></a></li>
          </div>
    {% endblock %}
    </header>

    {% comment %} <section id="slider">
        <div class="slider-container">
            <div class="slides">
                <img src="{% static 'img/1.jpg' %}" alt="slide1" class="active">
        </div>
    </section> {% endcomment %}

    <section id="slider">
      <div class="slider-container">
          <div class="slides">
              <img src="{% static 'img/1.jpg' %}" alt="slide1" class="active">
              <img src="{% static 'img/2.jpg' %}" alt="slide2">
              <img src="{% static 'img/3.jpg' %}" alt="slide3">
              <img src="{% static 'img/4.jpg' %}" alt="slide4">
              <img src="{% static 'img/5.jpg' %}" alt="slide5">
          </div>
          <div class="dots-container">
              <span class="dot active" onclick="currentSlide(1)"></span>
              <span class="dot" onclick="currentSlide(2)"></span>
              <span class="dot" onclick="currentSlide(3)"></span>
              <span class="dot" onclick="currentSlide(4)"></span>
              <span class="dot" onclick="currentSlide(5)"></span>
          </div>
      </div>
  </section>


    <div class="col-sm-10 ">
          {% block content %}
              
          {% endblock %}
          {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                    {% endif %}
                                    <span class="page-current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                {% endblock %}

        </div>
      </div>

{% block extra_js %}{% endblock extra_js %}
      <!----------------------- footer-------------------------->
<div class="footer_top">
  <div class="wraptem">
      <span class="img">
          <img src="{% static 'img/icon 1.png' %}" alt="icon">
      </span>
      <div class="content_right">
          <p>SHIP COD TOÀN QUỐC</p>
          <span>Miễn phí vận chuyển toàn quốc cho đơn hàng từ 999.000 đ</span>
      </div>
  </div>
  <div class="wraptem">
      <span class="img">
          <img src="{% static 'img/icon 2.png' %}" alt="icon">
      </span>
      <div class="content_right">
          <p>CHẤT LƯỢNG TUYỆT ĐỐI 100%</p>
          <span>Cam kết sản phẩm chính hãng</span>
      </div>
  </div>
  <div class="wraptem">
      <span class="img">
          <img src="{% static 'img/icon 3.png' %}" alt="icon">
      </span>
      <div class="content_right">
          <p>THANH TOÁN DỄ DÀNG</p>
          <span>Phương thức thanh toán đa dạng và cực kỳ tiện lợi</span>
      </div>
  </div>
  <div class="wraptem">
      <span class="img">
          <img src="{% static 'img/icon 4.png' %}" alt="icon">
      </span>
      <div class="content_right">
          <p>TIẾT KIỆM THỜI GIAN</p>
          <span>Mua sắm dễ hơn khi Online</span>
      </div>
  </div>
</div>
<div class="background">
  <div class="footer_bottom">
  <li> <h2>Book.vn</h2>
      <ul>
          <li>Số 32, Đường số 6 nhà ở khu Z756, Phường 12, Quận 10, Thành phố Hồ Chí Minh</li>
          <li>Số điện thoại:1900 1093 </li>
          <li>gmail:ecom@sneakerbuzz.vn</li>
          <li>Công ty TNHH TM&DV Phú Vỹ. Giấy chứng nhận Đăng ký Kinh doanh số 0313679661 do Sở Kế hoạch và Đầu tư Thành phố Hồ Chí Minh cấp ngày 07/03/2016</li>
          <li><img src="{% static 'img/thongbao.webp' %}" alt="bộ công thuong"></li>
      </ul>
  </li>
  <li> <h2>DANH MỤC</h2>
      <ul>
          <li>Sach</li>
          <li>Tác giả</li>
      </ul>
  </li>
  <li> <h2>CHÍNH SÁCH</h2>
      <ul>
          <li>Điều khoản & điều kiện</li>
          <li>Chính sách bảo mật</li>
          <li>Chính sách giao hàng</li>
          <li>Chính sách bảo hành</li>
          <li>Chính sách đổi trả</li>
          <li>Phương thức thanh toán</li>
          <li>Hướng dẫn đặt hàng</li>
          <li>Câu hỏi thường gặp</li>
          <li>Liên Hệ Hợp Tác</li>
          <li>Chính sách ưu đãi khách hàng mới</li>
      </ul>
  </li>
  <li> <h2>TIN TỨC</h2>
      <ul>
          <li>THỜI TRANG</li>
          <li>KHUYẾN MÃI</li>
          <li>LOOKBOOK</li>
      </ul>
  </li>
</div>
</div>
  </body>
</html>

catalog/templates/books_per_author.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Số sách với mỗi tác giả trong hệ thống</h1>
  <img src="data:image/png;base64,{{ graph }}" alt="Books per Author Graph">
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h2 id="san_pham_moi">TẤT CẢ SẢN PHẨM</h2>
<section class="cartegory">
  {% for book in book_list%}
    <div class="container_san_pham_moi">
        <div class="iterm">
            <img src="" alt="">
            <h1>{{book.title}}</h1>
            <h1>{{book.author}}</h1>
        </div>
      </div>
  {% endfor %}
</section>
{% endblock %}